version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always
    # Dev mode: mount code and enable hot reload
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis
    command: ["celery", "-A", "celery_app.celery_app", "worker", "--loglevel=info", "-Q", "audit,keyword,competitor_analysis"]
    restart: always

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install -g pnpm && pnpm install && pnpm dev --host"]
    depends_on:
      - backend
    restart: always
    # Dev mode: mount code and run Vite dev server with hot reload

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tldseo
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    # ports:
    #   - "6379:6379"
    restart: always

volumes:
  pgdata: 