"""Updated audit model to store all the details

Revision ID: 10efe198bfa2
Revises: e897c8c5d431
Create Date: 2025-06-27 18:42:19.210645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10efe198bfa2'
down_revision: Union[str, Sequence[str], None] = 'e897c8c5d431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_reports', sa.Column('url', sa.String(), nullable=True))
    op.add_column('audit_reports', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_reports', 'timestamp')
    op.drop_column('audit_reports', 'url')
    # ### end Alembic commands ###
