"""added competitor analysis table

Revision ID: 1c1be6395bd3
Revises: c6d054c89e08
Create Date: 2025-07-09 23:14:35.068369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c1be6395bd3'
down_revision: Union[str, Sequence[str], None] = 'c6d054c89e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_analyses', sa.Column('user_url', sa.String(length=500), nullable=False))
    op.add_column('competitor_analyses', sa.Column('competitor_urls', sa.JSON(), nullable=False))
    op.add_column('competitor_analyses', sa.Column('competitor_keywords', sa.JSON(), nullable=False))
    op.add_column('competitor_analyses', sa.Column('content_gaps', sa.JSON(), nullable=False))
    op.add_column('competitor_analyses', sa.Column('recommendations', sa.JSON(), nullable=False))
    op.alter_column('competitor_analyses', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_column('competitor_analyses', 'domain_authority')
    op.drop_column('competitor_analyses', 'competitor_name')
    op.drop_column('competitor_analyses', 'organic_keywords')
    op.drop_column('competitor_analyses', 'page_authority')
    op.drop_column('competitor_analyses', 'backlink_gap_score')
    op.drop_column('competitor_analyses', 'content_similarity_score')
    op.drop_column('competitor_analyses', 'analysis_data')
    op.drop_column('competitor_analyses', 'paid_keywords')
    op.drop_column('competitor_analyses', 'referring_domains')
    op.drop_column('competitor_analyses', 'total_backlinks')
    op.drop_column('competitor_analyses', 'keyword_overlap_score')
    op.drop_column('competitor_analyses', 'competitor_url')
    op.drop_column('competitor_analyses', 'organic_traffic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_analyses', sa.Column('organic_traffic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('competitor_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('competitor_analyses', sa.Column('keyword_overlap_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('total_backlinks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('referring_domains', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('paid_keywords', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('analysis_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('content_similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('backlink_gap_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('page_authority', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('organic_keywords', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('competitor_analyses', sa.Column('competitor_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('competitor_analyses', sa.Column('domain_authority', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('competitor_analyses', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('competitor_analyses', 'recommendations')
    op.drop_column('competitor_analyses', 'content_gaps')
    op.drop_column('competitor_analyses', 'competitor_keywords')
    op.drop_column('competitor_analyses', 'competitor_urls')
    op.drop_column('competitor_analyses', 'user_url')
    # ### end Alembic commands ###
