"""add refresh token fields to user

Revision ID: 335b38eb660e
Revises: 1c1be6395bd3
Create Date: 2025-07-10 21:43:33.015795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335b38eb660e'
down_revision: Union[str, Sequence[str], None] = '1c1be6395bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=32), nullable=False, server_default='local'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expiry')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
