"""added is_verified to user

Revision ID: 49ae3c4e41c8
Revises: f73440c090d6
Create Date: 2025-06-25 20:46:01.342038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49ae3c4e41c8'
down_revision: Union[str, Sequence[str], None] = 'f73440c090d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_reports', 'search_console_data')
    op.drop_column('audit_reports', 'total_clicks')
    op.drop_column('audit_reports', 'average_ctr')
    op.drop_column('audit_reports', 'total_impressions')
    op.drop_column('audit_reports', 'average_position')
    op.drop_column('projects', 'search_console_property')
    op.drop_column('projects', 'target_language')
    op.drop_column('projects', 'target_location')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_token_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expiry')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.add_column('projects', sa.Column('target_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('target_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('search_console_property', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('audit_reports', sa.Column('average_position', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('audit_reports', sa.Column('total_impressions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_reports', sa.Column('average_ctr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('audit_reports', sa.Column('total_clicks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_reports', sa.Column('search_console_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
