"""made changes in auditreport model

Revision ID: e897c8c5d431
Revises: 46bc6191e744
Create Date: 2025-06-26 02:34:41.825092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e897c8c5d431'
down_revision: Union[str, Sequence[str], None] = '46bc6191e744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_reports', sa.Column('lighthouse_mobile', sa.JSON(), nullable=True))
    op.add_column('audit_reports', sa.Column('lighthouse_desktop', sa.JSON(), nullable=True))
    op.drop_column('audit_reports', 'issues_found')
    op.drop_column('audit_reports', 'technical_score')
    op.drop_column('audit_reports', 'content_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_reports', sa.Column('content_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_reports', sa.Column('technical_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_reports', sa.Column('issues_found', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_reports', 'lighthouse_desktop')
    op.drop_column('audit_reports', 'lighthouse_mobile')
    # ### end Alembic commands ###
